### ISSUE TITLE
Error and Disconnect on server join

### ISSUE THREAD

**Issue by FelipeCardona95** [blaxxun-boop/Professions#5]
Hi Boop, I have some mods added to my server and Im trying to join mine, when I do so I get a NullRef error in the console, this is the output
https://pastebin.com/mxR61fZD
Disabling profession lets me join my server with no issue, is this and issue only on professions or its something rrelated to better continents? since I see its included in the error

**Comment by blaxxun-boop** [comment]
Better Continents stopped working a long time ago. The author said he might be back for Mistlands and fix it.

**Comment by FelipeCardona95** [comment]
> Better Continents stopped working a long time ago. The author said he might be back for Mistlands and fix it.

But Better continents work when professions is not present so saying it stopped working a long time ago wouldnt be mistaken?
