### ISSUE TITLE
Alchemy group buffs stripping all other damage

### ISSUE THREAD

**Issue by fadinginterest** [blaxxun-boop/Professions#6]
All of the potions that give group buffs (like Cunning Toxicity for poison damage) are bugged. Instead of adding an elemental damage on top of existing damage, they are disabling all other damage and Only allowing the elemental buff. So when a group under the buff attacks they are ONLY doing the small bit of elemental damage. Also the xp curve for Alchemy is significantly steeper than the other professions. It would be great to be able to adjust this or have it increased. Thanks!

**Comment by blaxxun-boop** [comment]
That is exactly how they are supposed to work.
